name: Deploy to ECR

on:
 
  push:
    branches: [ main ]
  
env:
  ECR_REGISTRY: public.ecr.aws/329667351664

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
  
    permissions:
      id-token: write # obrigatório para usar autenticação OIDC
      contents: read # obrigatório para clonar o código do repositório'
   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLEARN }}
        role-duration-seconds: 900 # o TTL da sessão, em segundos.
        aws-region: us-east-1 # sua região

    - name: Login to Amazon ECR
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Build, tag, and push image to Amazon ECR
      env:
        IMAGE_NAME: docker-python3
        IMAGE_TAG: ${{ github.sha }}
        ECR_REPOSITORY: docker-python
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
